// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAW1ORxUQ_uy3g2gg9_wvQ2lKK9SpFgQA',
    appId: '1:1070260106771:web:1750b9f4cc38dbc38671e6',
    messagingSenderId: '1070260106771',
    projectId: 'worknote-cd463',
    authDomain: 'worknote-cd463.firebaseapp.com',
    storageBucket: 'worknote-cd463.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3Dxh9mnXFfaN5X2M2SbyE2tdHy5JJHk',
    appId: '1:1070260106771:android:5dbdd60de061b6268671e6',
    messagingSenderId: '1070260106771',
    projectId: 'worknote-cd463',
    storageBucket: 'worknote-cd463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1lEKI9BtaVcNmTRwh4no-WBurPqneSbs',
    appId: '1:1070260106771:ios:13e642eaf47c7bf98671e6',
    messagingSenderId: '1070260106771',
    projectId: 'worknote-cd463',
    storageBucket: 'worknote-cd463.firebasestorage.app',
    iosBundleId: 'com.example.worknote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1lEKI9BtaVcNmTRwh4no-WBurPqneSbs',
    appId: '1:1070260106771:ios:13e642eaf47c7bf98671e6',
    messagingSenderId: '1070260106771',
    projectId: 'worknote-cd463',
    storageBucket: 'worknote-cd463.firebasestorage.app',
    iosBundleId: 'com.example.worknote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAW1ORxUQ_uy3g2gg9_wvQ2lKK9SpFgQA',
    appId: '1:1070260106771:web:3b68716a1003493b8671e6',
    messagingSenderId: '1070260106771',
    projectId: 'worknote-cd463',
    authDomain: 'worknote-cd463.firebaseapp.com',
    storageBucket: 'worknote-cd463.firebasestorage.app',
  );

}